services:
  outlook-register:
    build: .
    image: outlook-auto-register:local
    container_name: outlook-auto-register
    ports:
      - "8890:8890"
    env_file:
      - .env
    environment:
      DISPLAY: ":99"
      PX_SOLVER: swiftshader
      PX_SWIFTSHADER_HEADFUL: "1"
      PX_SWIFTSHADER_TARGET: parent
      PX_PRESS_BACKEND: xdotool
      OUTLOOK_DB_PATH: /app/data/outlook.db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapp.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.myapp.entrypoints=websecure"
      - "traefik.http.routers.myapp.tls=true"
      - "traefik.http.services.myapp.loadbalancer.server.port=8890"
    volumes:
      - ./data:/app/data
      - ./accounts:/app/accounts
    restart: unless-stopped
    shm_size: "1gb"
    networks:
      - proxy

networks:
  proxy:
    external: true
